### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by ferdymercury** [PerkLab/SlicerSkinMouldGenerator#1]
Hello, thanks for this contribution.

I was wondering if this extension is accessible via the Extension Manager? I could not find it.

If not, how is the recommended way to run it? Clone the repository and then import it somehow in Slicer?

Cheers.

**Comment by lassoan** [comment]
See the discussion here:

https://discourse.slicer.org/t/cutting-plan-in-3d-slicer-v-4-6/25176

**Comment by lassoan** [comment]
The extension is compatible with Slicer-5.0.3 now.
